### ISSUE TITLE
"ender_flower" crash

### ISSUE THREAD

**Issue by LokyLive** [p455w0rd/EndermanEvolution#26]
Hey i get a crash with my custom modpack, i don't understand what is exactly the problem i've just see Primal Core and Ender_flower in the crash log 

[crashlog](https://pastebin.com/4WcniEBa)

**Comment by p455w0rd** [comment]
from what I can tell, it's not on my end..and since the primal core dev doesnt care about helping the community by keeping his mod open source, I won't be looking into his side of things to be able to see for sure if it's their mod or mine...convince them to do the right thing and put the source on github and i'll check it out..otherwise..sorry :/

**Comment by p455w0rd** [comment]
fixed it on my end..thanks for the report! :D
