### ISSUE TITLE
[1.12.2] Support for Multi Storage by ShetiPhian

### ISSUE THREAD

**Issue by brisingraerowing** [p455w0rd/EndermanEvolution#3]
I use Multi Storage for ender link chests and stuff as it also adds a few other things I like, such as multiblock indestructible vaults, so having that supported in addition to Ender Storage would be quite useful.

[Here's the mod's Curseforge page](https://minecraft.curseforge.com/projects/multistorage)

**Comment by p455w0rd** [comment]
I'll think about it. I originally didn't like the mod because it was a blatant rip off of Ender Storage...but it has been expanded a lot....I'll think about it

**Comment by p455w0rd** [comment]
I was going to implement this, so I started to do research on what would be required. Tried finding the source, only to find out, it's closed-source. So, in order to do this and be able to render the chests, I'd have to decompile the mod. Thanks to their selfish licensing, I am not legally able to do this. Sorry.
