### ISSUE TITLE
Ticked Entity crashing server

### ISSUE THREAD

**Issue by dd957** [p455w0rd/EndermanEvolution#40]
This mod crashes my server only after a first player joins with the Ticked Entity error.

Crash report here: [https://pastebin.com/6xdHiz1G](url)

**Comment by p455w0rd** [comment]
Please report this to LLibrary. They are trying to get a capability without even checking that the entity has that capability. [link](https://github.com/iLexiconn/LLibrary/blob/1.12.2/src/main/java/net/ilexiconn/llibrary/server/capability/EntityDataHandler.java#L50)

At minimum they definitely should __NOT__ throw an exception if they aren't using `Entity#hasCapability` to first check. In this case, `null` is equivalent to a `Entity#hasCapability` check, but instead of logically terminating silently, they throw an exception. This is on their end.
