### ISSUE TITLE
re-implement light level config

### ISSUE THREAD

**Issue by PiggyWhiskey** [p455w0rd/EndermanEvolution#8]
Playing Modern Skyblock 3 on my private server,
Server and Client both have the setting to False.
The only unlit area is 2 blocks tall, and is enclosed in a mob farm.
Spawns are still occurring.

EndermanEvolution 1.0.5

**Comment by p455w0rd** [comment]
from the CurseForge project page: ![](http://p455w0rd.net/u/08.37.46-04.02.18.png)

**Comment by p455w0rd** [comment]
This is just a config i forgot to remove, otherwise, they're essentially no different than vanilla Enderman. I can probably re-enable it if this is actually wanted, but, as I said, this kinda makes them pointless

**Comment by PiggyWhiskey** [comment]
So what's the point of the config option disabling that?

**Comment by p455w0rd** [comment]
I'm working on re-adding the light level stuff (actually done and functional) but running into other issues like the max per group number being ignored..next update, this will work, if you'd like to test it,, join my discord and I can send you a copy before a post to curse

**Comment by PiggyWhiskey** [comment]
We posted a comment at the same time...
I'm okay with them, but I'd like the option to control where they spawn.
I'm not a fan of random mobs running up and down my base, but if they're outside....no problems.

**Comment by p455w0rd** [comment]
so the real issue is spawn probability..looking through code (and I could be wrong), it appears that forge is ignoring the parameters and is instead awaiting a result from an event (which I don't listen for and _should_ have no reason to listen for)..therefore, It's always defaulting to 4..there's also something funny about the weighting..even when probability is set to 1, they're spawning too often
